### ISSUE TITLE
Add option to "deploy" command in order to add a prefix string to commit message

### ISSUE THREAD

**Issue by VerrNum** [jimporter/mike#107]
In order to match the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) , could you provide a way to add prefix string to commit message ?

Regards,

**Comment by jimporter** [comment]
There's a `--message` option to do this, though you'd have to fill in the commit SHA and such yourself if you wanted to include that.

**Comment by jimporter** [comment]
I think with the `--message` option and the fact that you can do subshell expansions to grab info about the deploy process, this is already supported. For example, you could explicitly set the same message that mike does automatically like:

```
mike deploy $VERSION --message \
"Deployed `git rev-parse HEAD` to $VERSION with `mkdocs --version | sed -e 's/, version//' -e 's/ from.*//'` and `mike --version`"
```
