### ISSUE TITLE
Mike deploy not updating to latest version 

### ISSUE THREAD

**Issue by kiroalbatrosa** [jimporter/mike#108]
Hello,

I am using pages in github enterprise, when adding a new version to my documentation via acions(it is triggered by pushing/commiting to the docs folder in the main branch.

The automation calls a script on the listener that pulls the current repo and updates the pages site with mike deploy, for example:
mike deploy --push --update-aliases 0.15 latest

What I observe is that :
1) The latest tag is not reflected in the versions.json file in the gh-pages branch, the tag stays with the previous version.
2) When executing the push command either manualy or via the pipeline, the update is reflected on the previous version(the one that has the latest tag)

How do I resolve this and make the deploy command act as it should- update specified version as given?

**Comment by jimporter** [comment]
This is difficult to debug without seeing the configs and your commit logs, but here are some things you can try:
* Make sure you're not using a shallow clone of the `gh-pages` branch
* Look at the diffs of the commits generated by mike to see what it's doing
* Try running `mike deploy` locally without pushing and then use `mike serve` to view the current state of your `gh-pages` branch

**Comment by jimporter** [comment]
Have you looked at the diff of the commit generated by mike *before* pushing? That might give you more information. I'd be extremely surprised if the command you showed actually generated that commit.

You could also try deploying to a different branch (`--branch foobar`) or testing on a different repository entirely.

If those don't work, the only thing left you could do is to run mike in a debugger and step through the entire process.

**Comment by jimporter** [comment]
Yes, the latest dev version has a `mike --debug` flag (it goes *before* the subcommand name). I'm not sure it'll tell you a whole lot that my other suggestions wouldn't, but you can try it.
