### ISSUE TITLE
Versioning is not showing in GUI

### ISSUE THREAD

**Issue by KarthikModelon** [jimporter/mike#111]
I have created the versioning in the website but it is not showing up in the GUI.
![image](https://user-images.githubusercontent.com/109127978/180158431-32793bdb-5ab0-47ba-9542-d6ec5b095642.png)
![image](https://user-images.githubusercontent.com/109127978/180158658-5d345c7a-fce6-4ce5-ab7e-4234bf492490.png)
Also I have added the css and java script as per the documents. But the version selector is not showing

**Comment by jimporter** [comment]
That's the Material theme, so you'll have to make sure to configure things according to [Material's documentation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/). I don't have any involvement with Material, so I can't really help you.
