### ISSUE TITLE
No Version selector and error in mike serve logs

### ISSUE THREAD

**Issue by bitchaser12** [jimporter/mike#113]
I followed the mike and mkdocs-material tutorials. My site is up and has the version in the url address and appears to version correctly if I manually change the version in the url. However, there is no version selector and mike is flooding the chat with the following message:
127.0.0.1 - - [01/Sep/2022 09:14:54] code 404, message File not found
127.0.0.1 - - [01/Sep/2022 09:14:54] "GET /livereload/865877890/865878312 HTTP/1.1" 404 -

**Comment by jimporter** [comment]
Do you have a repository I could look at with your configuration and the generated HTML? It's difficult to diagnose errors like this without seeing the full setup.

**Comment by jimporter** [comment]
You could try using one of the built-in themes (e.g. `mkdocs`) to see whether this is a configuration issue with the Material theme. You might also want to look at whether the `gh-pages` directory structure looks right. It should be something like:

```
/1.0
    index.html
    ...
/2.0
    index.html
    ...
.nojekyll
index.html
versions.json
```

Finally, you can check the commit logs on the `gh-pages` branch to make sure that everything looks reasonable. It should provide some information about how the pages were generated (Mkdocs/mike versions plus the source commit SHA).

**Comment by jimporter** [comment]
You probably didn't fully delete the branch. Per the [documentation](https://github.com/jimporter/mike#staying-in-sync), to keep in sync with upstream changes, mike will "automatically update your local branch to match the remote's if possible (note that mike won't automatically git fetch anything)". I'm guessing you left `origin/gh-pages` in your local clone.

You shouldn't need to delete it anyway; if you want a fresh state, you can run `mike delete --all`, which just adds a new commit that removes all the files from the `gh-pages` branch.

**Comment by jimporter** [comment]
The only `1.1` I see in the log is `HTTP/1.1`, but that's just the version of the HTTP protocol being used. The logs look like it's doing something weird with livereload. Since `mike serve` doesn't use livereload, I don't think that's a mike issue.

Do you happen to have an old tab open from looking at local docs generated by `mkdocs serve`? That would probably issue requests to livereload until you get rid of that tab...
