### ISSUE TITLE
Absolute links break site?

### ISSUE THREAD

**Issue by magnusg-sa** [jimporter/mike#115]
Do I understand correctly that Mike does not work with absolute links?

For example, if the page `http://mydocs.com/4.14/basic-functions/` has a link

```
Navigate to [Docs->Topics](/topic) for...
```

That should take the user to `http://mydocs.com/4.14/topic`, but instead it takes the user to `http://mydocs.com/topic` which of course does not exist. So my question is: does Mike only work with relative links? Or am I missing some vital detail in the documentation?

**Comment by jimporter** [comment]
Yeah, that's the expected behavior. An absolute path would resolve relative to the root of your domain. This isn't a mike-specific issue though, since MkDocs itself strongly recommends the use of relative paths for links: https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages

**Comment by magnusg-sa** [comment]
That's very unfortunate. Thank you for your swift reply!
