### ISSUE TITLE
Using mkdocs `-s` option to build docs in strict mode

### ISSUE THREAD

**Issue by moritzmeister** [jimporter/mike#117]
Hi! Thanks for this great extension to mkdocs.

I would like to use the "strict" mode of mkdocs when building, so that the build fails if there are any warnings.
Is there a way to pass this option down to mkdocs when using `mike deploy`?

```
  -s, --strict                    Enable strict mode. This will cause MkDocs
                                  to abort the build on any warnings.
```

**Comment by jimporter** [comment]
Yes, you can specify that in your `mkdocs.yml`: https://www.mkdocs.org/user-guide/configuration/#strict

**Comment by moritzmeister** [comment]
Ah thanks, I missed that!
