### ISSUE TITLE
Error in deploying using mike - config not found

### ISSUE THREAD

**Issue by nehatharani** [jimporter/mike#12]
Hi, 

I am trying to created versioned docs using Mike. I read that now there is a support for material theme.  I did everything as per the readme.md but as soon I try to deploy I get the following error - 
mike: error getting config: 

My folder structure is: 

Versioning(git repo tag: dev)
-->Versioned_docs\
---->docs\
----> mkdocs.yml
----> site\

I have done ``` mike install-extras``` before deploy. Am I missing any obvious steps? 

mkdocs.yml: 

```
site_name: My Docs
theme:
  name: material
extra_css:
- css\version-select.css
extra_javascript:
- js\version-select.js


```

**Comment by jimporter** [comment]
Are you running the deploy subcommand from within your repo, and do you have `user.name` and `user.email` set in your git config? mike needs that info since it's generating a commit on your behalf.

**Comment by nehatharani** [comment]
Hi, 
I added this information and now when I do mike serve it get nothing. 
```
 code 404, message File not found
127.0.0.1 - - [28/Feb/2020 15:18:28] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [28/Feb/2020 15:18:33] code 404, message File not found
127.0.0.1 - - [28/Feb/2020 15:18:33] "GET /livereload HTTP/1.1" 404 -
```

When I do ```mkdocs serve``` I do pages served on localhost but there is not versioning/ version drop down. 

My repo lies in azure devops.

**Comment by jimporter** [comment]
If you want to redirect users from the root of your site, you'll need to set a default docs version to redirect to via `mike set-default`: https://github.com/jimporter/mike#setting-the-default-version

**Comment by nehatharani** [comment]
Right. I have set up the default version as DEV. I have a web server configured for document deployment. I do see a small drop sown but it disappears when I select an option. 
![image](https://user-images.githubusercontent.com/42864611/75692121-5bef7380-5ca5-11ea-860c-e02e50b90830.png)

Both versions are deployed with dev being the default.

**Comment by jimporter** [comment]
@nehatharani Ok, looks like there's a bug with showing the version selector on the main page of the docs. Can you try applying this patch to the copy of `version-select.js` in your repo?

```patch
diff --git a/js/version-select.js b/js/version-select.js
index 0c75a9e..06a35bf 100644
--- a/js/version-select.js
+++ b/js/version-select.js
@@ -1,7 +1,7 @@
 window.addEventListener("DOMContentLoaded", function() {
   // This is a bit hacky. Figure out the base URL from a known CSS file the
   // template refers to...
-  var ex = new RegExp("/assets/fonts/material-icons.css$");
+  var ex = new RegExp("/?assets/fonts/material-icons.css$");
   var sheet = document.querySelector('link[href$="material-icons.css"]');

   var REL_BASE_URL = sheet.getAttribute("href").replace(ex, "");
```

If that works, then I'll publish a new release of mike with that fix. Thanks!

**Comment by nehatharani** [comment]
Done. It did solve the issue. When I select the version from drop-down, it navigates to the new version but there is no way to get back to previous version as drop-down disappears. 
Here are first few lines of version-select.js
```java
window.addEventListener("DOMContentLoaded", function() {
  // This is a bit hacky. Figure out the base URL from a known CSS file the
  // template refers to...
  var ex = new RegExp("/?assets/fonts/material-icons.css$");
  var sheet = document.querySelector('link[href$="material-icons.css"]');

  var REL_BASE_URL = sheet.getAttribute("href").replace(ex, "");
```

**Comment by jimporter** [comment]
> Done. It didn't solve the issue. When I select the version from drop-down, it navigates to the new version but there is no way to get back to previous version as drop-down disappears.

Did you update the JS for *both* versions of the docs?

**Comment by jimporter** [comment]
This should be resolved.
