### ISSUE TITLE
Setting a subdirectory for the docs

### ISSUE THREAD

**Issue by sammaphey** [jimporter/mike#120]
I notice in your readme you enable setting a `--deploy-prefix ` when running `mike deploy` or a `deploy_prefix` in the plugins section, but I get these errors:

![image](https://user-images.githubusercontent.com/20199103/200022192-e537399d-8833-4c04-b37b-dec7df7a2ae5.png)

![image](https://user-images.githubusercontent.com/20199103/200022391-48fc1a81-d5fa-4f67-bc7c-5f291fb81b11.png)

It looks like perhaps they are not present int he most recent release?

**Comment by jimporter** [comment]
If you're using the most recent release, [this](https://github.com/jimporter/mike/blob/v1.1.2/README.md) is the README you should look at. In 1.1.2, the flag is `--prefix`.

**Comment by sammaphey** [comment]
Ahh okay, thanks!

**Comment by snoyiatk** [comment]
Is there anyway to set default prefix via mkdocs.yml files?

**Comment by jimporter** [comment]
Yes. As implied above, upgrade to the latest Git revision and use `plugins.mike.deploy_prefix`.

**Comment by snoyiatk** [comment]
Do you have any suggestion/comment on why my mkdocs configuration doesn't work :(

**Comment by jimporter** [comment]
You can't use `plugins.mike.deploy_prefix` on v1.1.2. As mentioned, you need the latest development version from Git if you want to use that. Otherwise, use `--prefix` on the command line.

**Comment by bitsondatadev** [comment]
@jimporter, any idea when the next release will be? It would be convenient to have the mkdocs config available to add to GitHub actions. Since you're running this for free, `--prefix` will do until you have time to cut a release. Thank you so much for this amazing tool!
