### ISSUE TITLE
Redirect traffic for "unrecognized" url paths

### ISSUE THREAD

**Issue by sammaphey** [jimporter/mike#121]
Is there a way to redirect a request for an unrecognized url to the new path but prepended with `latest` (or whatever you default is)?

For example, if I try to got to `http://localhost:800/tutorial/advanced` I receive a 404 error, but I would like to be forwarded to `http://localhost:800/latest/tutorial/advanced`.

Perhaps this is something that can already be done in Material for mkdocs, though I have not found it

**Comment by jimporter** [comment]
This is the same as #72, and planned for 2.0.
