### ISSUE TITLE
add support for golang vanity url

### ISSUE THREAD

**Issue by rchincha** [jimporter/mike#126]
https://github.com/jimporter/mike/blob/49cf9c8925d86847b6dbfbf82ce6fa4aa428e4e0/mike/templates/redirect.html#L7

https://medium.com/@JonNRb/making-a-golang-vanity-url-f56d8eec5f6c

**Comment by jimporter** [comment]
You should be able to do this the same way you might add a `CNAME` file to your docs: https://github.com/jimporter/mike#cname-and-other-special-files

**Comment by rchincha** [comment]
https://github.com/jimporter/mike/blob/master/mike/templates/redirect.html
^ this?

If I have 
/
-docs/
-template/my-redirect.html

So in the plugin config
redirect_template: template/my-redirect.html

^ would this work?

**Comment by jimporter** [comment]
If you're on the latest dev builds, yes. On the 1.x releases, you'll need to use `--template`.
