### ISSUE TITLE
Allow a "bleeding-edge" alias

### ISSUE THREAD

**Issue by sammaphey** [jimporter/mike#128]
My documentation releases version in the following manner:

- RC release (mapped to my develop branch), example version is 1.0.10-rc1
- Major release (mapped to my main branch), example version is 1.0.10

I want a way to have a similar capability that is outline in [mkdocs material's outdated section](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/?h=mike#version-warning) but for "bleeding-edge" docs. I believe this might be capable by utilizing mike, though I think something might need to change, for example, when viewing an "old" version of the documentation mkdocs knows it is outdates because the alias in mike is not "latest". However there can only be **one** latest version. With bleeding edge docs there may be multiple, for example, I have a global epic for adding a new search tool to my app that encompasses a few different features, so I might have 4 RC versions before a major release, where all of them should be marked as "bleeding-edge"

Not sure which part of this would be on you and which is on mkdocs, but I think this would be a useful feature

**Comment by jimporter** [comment]
mike doesn't have any concept of what versions are outdated or not; that's a feature of the MkDocs Material theme, so you'll have to ask there.
