### ISSUE TITLE
JS file with Material Theme `install-extras` doesn't work

### ISSUE THREAD

**Issue by pblitz** [jimporter/mike#14]
On a brand new mkdocs (1.1) and a new mkdocs-material (4.6.3) project, executing `mike install-extras` correctly installs the necessary elements, but the script installed doesn't work.
Looks like there is a typo in there - instead of loading the versions.json from the absolute URL, it tries to load it from the relative URL.. which at least in my browser doesn't work.

**Comment by jimporter** [comment]
This is actually a dupe of #12, though I haven't landed the fix in that issue yet. I'll do that in a bit...
