### ISSUE TITLE
I need a bit of help

### ISSUE THREAD

**Issue by stantios** [jimporter/mike#140]
Description: I would like to add a version and then commit something to that version. I've already setup one version which is 5.7.1 but how would I add another one and keep 5.7.1 as a version? This is what the build script looks like for the docs: https://github.com/Imzxhir/journeymap-docs/blob/main/.github/workflows/deploy.yml

**Comment by jimporter** [comment]
> So, would `mike deploy --push --update-aliases 5.8.5 latest -F ./config/en/mkdocs.yml` after running `git fetch origin gh-pages --depth=1` and removing the --force work?

Something like that should work.

> I've now removed the --force command from deploy.yml as seen here https://github.com/Imzxhir/journeymap-docs/blob/main/.github/workflows/deploy.yml

Yes, but you didn't remove the `mkdocs gh-deploy` step. That really does need to go, since it publishes *unversioned* documentation, which you almost certainly don't want.

I'd recommend filing an issue with the Material theme about improving their documentation.

**Comment by jimporter** [comment]
It really depends on the workflow you'd like for your project, so I'm not in a position to say what you need to do (except in very general terms).

If you want to add a new version (for example, you previously deployed `1.0` and now want to deploy `2.0`), then you can just run `mike deploy 2.0`. The old 1.0 docs will still be there, but now you have a new set of docs for 2.0. Of course, you can also add aliases for this new version, so if you had previously run `mike deploy 1.0 latest`, you might want to mark your new 2.0 docs as `latest` now: `mike deploy 2.0 latest --update-aliases`.

To get a better feel for how this works, I'd recommend first reading through all the documentation on [building your docs](https://github.com/jimporter/mike#building-your-docs), and then trying it out locally. Just call `mike deploy ...` without pushing upstream, and then use `mike serve` to create a local webserver to check things out. Once you feel like you've found a process that you're happy with, only *then* add this to your Github CI.

**Comment by jimporter** [comment]
Correct.
