### ISSUE TITLE
Has anyone tested mike with the mkdocs material theme?

### ISSUE THREAD

**Issue by jgarte** [jimporter/mike#146]
Hi,

Has anyone tested mike with the mkdocs material theme?

ps

Would it be possible to enable Github Discussions?

**Comment by jimporter** [comment]
Yes, there's support, but the Material theme would be a better place for it.

**Comment by jimporter** [comment]
All the code for Material's integration with mike lives in their repo; long ago, mike used to provide some code to integrate with Material in this repo, but with explicit support from the Material devs, that's no longer necessary.
