### ISSUE TITLE
Deploy without build

### ISSUE THREAD

**Issue by samuelcolvin** [jimporter/mike#155]
I would like to use mike to deploy from a site that has already been build (in CI) - would be great if this was available as a separate command or argument to `mike deploy`.

**Comment by jimporter** [comment]
Sorry, but this isn't really possible (at least not without a lot of extra work). `mike deploy` doesn't *just* call `mkdocs build`; it inserts itself into the MkDocs build process and overrides some of the settings in your `mkdocs.yml` configuration based on the command-line arguments to `mike deploy`.

**Comment by samuelcolvin** [comment]
What about a `mike build` command that does build but leaves the new files in a directory in the current branch?

**Comment by jimporter** [comment]
That wouldn't work either, since it would also need special handling for the `versions.json` file in the root directory.

In practice, I think the way to do what you want would simply be to save the diff created by `mike deploy` (e.g. with `git format-patch`) and then apply it and push upstream when you want (e.g. with `git am`).

**Comment by samuelcolvin** [comment]
makes sense, thanks so much.

**Comment by jimporter** [comment]
Oh, I guess I should add: in general, one of the benefits (I hope) of mike is that every change is just a Git commit. That means that you can use any of the various Git subcommands to work with the mike-generated commits. So for example, my above suggestion is pretty close to the email-based Git workflow, where the author of a change sends a patch file to a mailing list via `git format-patch` or `git send-email`, and then the maintainer applies the patch via `git am`.
