### ISSUE TITLE
How to delete retitle?

### ISSUE THREAD

**Issue by luolingchun** [jimporter/mike#156]
I have two versions.

```bash
> mike list              
v2.x [latest]
v1.x
```

Now, I use `retitle`.

```bash
> mike retitle v2.x latest(v2.x)
> mike list
"latest(v2.x)" (v2.x) [latest]
v1.x
```

I want to delete `"latest(v2.x)"`.

I tried `mike retitle latest(v2.x) v2.x` and `mike delete latest(v2.x)`, but I got some errors.

```bash
> mike retitle latest(v2.x) v2.x 
error: version 'latest(v2.x)' does not exist
```
```bash
> mike delete latest(v2.x)
error: version KeyError(<LooseVersion('latest(v2.x)')>) does not exist
```

**Comment by jimporter** [comment]
"latest(v2.x)" is just a title, not a version (or alias) name, so you can't use it in places that expect a version/alias. To do what you want, all you need is `mike retitle v2.x v2.x`.
