### ISSUE TITLE
make a release

### ISSUE THREAD

**Issue by jnussbaum** [jimporter/mike#160]
Hi @jimporter,
I just wanted to ask if you plan to release a new version somewhat soon?
The last release is from October 2021, so we can't use the new features and bugfixes that you have worked on since then.

**Comment by jimporter** [comment]
I plan to tag a release sometime this year, but not particularly soon. In the meantime, you can just install from the latest dev version: `pip install git+https://github.com/jimporter/mike.git` (and possibly add `@some-hash` if you want to pin to a particular commit).

**Comment by jimporter** [comment]
If you'd like to see a release be published sooner, please help with the [2.0 release blockers](https://github.com/jimporter/mike/milestone/1) (though I strongly recommend commenting first with where you'd like to help so we can discuss strategy before you write any code).

**Comment by leonardehrenfried** [comment]
Thanks for the response. I will think about if I can give any time.
