### ISSUE TITLE
Support multiple projects under one mkdocs?

### ISSUE THREAD

**Issue by chipsenkbeil** [jimporter/mike#162]
My website is in the process of being built out with mkdocs material, and I have the need to support two different sets of documentation on the same website: a library/CLI and a neovim plugin.

These versions are distinct from each other, and I'd like to be able to reference a stable version of each and also support versioning of each.

For example, https://distant.dev/cli/0.20.x and https://distant.dev/neovim/0.3.x would be two separate projects housed under one mkdocs repository.

Is this something that's possible with the mike? Mkdocs material provides a provider for mike, and it was recommended to reach out here to see what (if any) solution mike could offer for this.

Reference discussion: https://github.com/squidfunk/mkdocs-material/discussions/5651

**Comment by jimporter** [comment]
You can do this. Just use `--deploy-prefix` (or `plugins.mike.deploy_prefix` in your `mkdocs.yml` on v2.x).

**Comment by jimporter** [comment]
That's correct. Each separately-versioned subdirectory would be a completely independent set of documentation.
