### ISSUE TITLE
Is there a way to include the version in the body of the docs (e.g. header)?

### ISSUE THREAD

**Issue by ilyagr** [jimporter/mike#167]
Could I make the landing page of the docs say "Welcome to docs version 0.8 (latest)"?

For example, does `mike` define some macro that could be used in the jinja templates or straight from markdown?

At the moment, the easiest way I can think of would be to edit `mkdocs.yml` before running `mike deploy`. I haven't thought through the exact way of passing that to the templates, but something along the lines of https://github.com/squidfunk/mkdocs-material/discussions/5803 might work.

Thank you for making Mike! I'm not sure if this is the right spot for questions, but I didn't find any other place to ask.

**Comment by jimporter** [comment]
> Could I make the landing page of the docs say "Welcome to docs version 0.8 (latest)"?
> 
> For example, does `mike` define some macro that could be used in the jinja templates or straight from markdown?

No, but you can use something like [mkdocs_macros_plugin](https://github.com/fralau/mkdocs_macros_plugin) to define a macro variable. That's what I do in [bfg9000](https://github.com/jimporter/bfg9000): see [mkdocs.py](https://github.com/jimporter/bfg9000/blob/master/mkdocs.py) in that repo to get started looking through the code. (Incidentally, that's the project that ultimately spawned mike in the first place.)

In particular, I'd strongly recommend any project that uses mike to have some file that stores your application's version string (e.g. `your-project/version.py`), and then consult that file when determining what version to pass to `mike deploy`, as well as any other place your version string might be useful (including `mkdocs_macros_plugin` in this case).

**Comment by jimporter** [comment]
> Thank you for making Mike! I'm not sure if this is the right spot for questions, but I didn't find any other place to ask.

You're welcome! I've enabled the "Discussions" feature on this repo on a trial basis, to see if it proves useful. It might make for a better place for support questions, and ideally others will feel freer to answer questions people have other there too.

**Comment by ilyagr** [comment]
Thank you, this is very helpful!
