### ISSUE TITLE
Versioning doesn't work if `site_dir` is set to a custom folder

### ISSUE THREAD

**Issue by masci** [jimporter/mike#17]
The folder containing builds' output defaults to `site` but it can be changed to something else in `mkdocs.yml` using [site_dir](https://www.mkdocs.org/user-guide/configuration/#site_dir). In my case that param was set to `public` and Mike wasn't able to build the versioned docs tree in the `gh-pages` branch with no errors.

I think the problem might be in [this function](https://github.com/jimporter/mike/blob/61c3d285072208db0e4138c1009e31c4db3d8e54/mike/mkdocs.py#L6) that assumes output must be collected from a directory called `site`.

I can change my output dir to `site` so it's not a big deal but the error is non obvious.

**Comment by jimporter** [comment]
Hm yeah, that's a problem. It should be fixable, but it'll take a bit of work since currently, `mike` only looks at the `mkdocs.yml` file to add the "extras". I'll need to add in the ability to read the config before we tell `mkdocs` to build...

**Comment by jimporter** [comment]
Ok, v0.5.2 is on PyPI with this fix.
