### ISSUE TITLE
Possibility to resolve default version without version tag in url

### ISSUE THREAD

**Issue by MarkusDressel** [jimporter/mike#172]
When using mike, each version is deployed under the respective version tag. So when building multiple version the url looks like this
* https://\<domain>.io/\<identifier>/ ... e.g 
* https://test.gitlab.io/stable/test-page ...

is it possible, to remove the identifier for a particular branch ? I would like to achieve the following:
* https://test.gitlab.io/test-page --> for default branch
* https://test.gitlab.io/dev/test-page --> for dev branch

**Comment by jimporter** [comment]
Sorry, but no it's not possible. By keeping each version as siblings, we can avoid any potential for conflicts where the top-level site overwrites another version. I'd much rather keep this tool simple, as it's already far more complex than I ever intended or wanted it to be.
