### ISSUE TITLE
[FEATURE] A smart version selector

### ISSUE THREAD

**Issue by frank-lenormand** [jimporter/mike#173]
Hi,

From what I could see, all versions of the documentation ever published are included in the selector.

I would like the selector to be able to show versions that _should_ be most relevant.

For example, assuming the versioning scheme is `major.minor`, it could show:

- the current version
- if the current version has a non-zero minor, show the previous two versions, up to the previous major
- _a separator to show the version chain is cut-off_
- the previous major with a zero minor

This feature could be opt-in, via a configuration option, or it could be implemented as part of the selector wheel (a tab? a checkbox? …).

Examples:

```
5.0
--
4.0
```

```
5.1
5.0
--
4.0
```

```
5.9
5.8
5.7
--
4.0
```

```
0.3
0.2
0.1
```

```
0.1
```

Thanks!

**Comment by jimporter** [comment]
I think this is really a matter best left to themes, or individual project authors. You can always adjust the exact behavior of the version selector by copying the existing JS/CSS for it and modifying the code to your liking.

It'll probably get easier to do something like that though when #138 is implemented. That would require adding extra properties to each version, but then your version selector code could consult that and do something about it.
