### ISSUE TITLE
Is it possible to use mkdocs --no-directory-urls option from mike?

### ISSUE THREAD

**Issue by jodygarnett** [jimporter/mike#204]
# Summary

I am migrating a project from sphinx-build to mkdocs, and would like to preserve the expectation that pages have `.html` suffix. 

The `mkdocs build` provides ``--no-directory-urls`` command line option for this -- is there a similar option for ``mike``?

# Configuration and Logs

* Repository: [](https://github.com/geonetwork/core-geonetwork/tree/main/docs/manual)
* Platform: Github Actions
* `mike` version: 2.0.0
* Commit generated by `mike`: https://github.com/geonetwork/core-geonetwork/commit/4d1f35261fdf553f39cdf5896c95187b3d2f9662
* CI configuration: https://github.com/geonetwork/core-geonetwork/blob/main/.github/workflows/docs.yml
* CI logs: https://github.com/geonetwork/core-geonetwork/actions/runs/7803014180/job/21281776099

# Expected Behavior

I had expected to be able to generate content with `html` output:

* https://docs.geonetwork-opensource.org/4.2/user-guide/quick-start/index.html (works)
* https://docs.geonetwork-opensource.org/4.2/user-guide/describing-information/creating-metadata.html (broken)

# Additional Context

The output using `mike` is here:

* https://docs.geonetwork-opensource.org/4.2/user-guide/quick-start/
* https://docs.geonetwork-opensource.org/4.2/user-guide/describing-information/creating-metadata/

The previous `sphinx-build` output is here:

* https://geonetwork-opensource.org/manuals/3.12.x/en/user-guide/quick-start/index.html
* https://geonetwork-opensource.org/manuals/3.12.x/en/user-guide/describing-information/creating-metadata.html

**Comment by jimporter** [comment]
Yes, just set [`use_directory_urls`](https://www.mkdocs.org/user-guide/configuration/#use_directory_urls) in your `mkdocs.yml`.

**Comment by jodygarnett** [comment]
Thanks, sorry I did not find that (sigh). I appreciate your work!
