### ISSUE TITLE
URL without version doesn't render version select

### ISSUE THREAD

**Issue by squidfunk** [jimporter/mike#21]
We've talked about integrating support for `mike` into Material for MkDocs some time ago, and I was advocating against it due to its JavaScript-driven approach. However, I've reconsidered given the benefits of its lightweight approach and I believe it would be a good addition. I've managed to set up a small test site with two versions, and it works as expected.

– https://squidfunk.github.io/mike-test/latest/
– https://squidfunk.github.io/mike-test/0.2/
– https://squidfunk.github.io/mike-test/0.1/

However, when I open https://squidfunk.github.io/mike-test/ (without the version string), the request in the console fails:

<img width="856" alt="Bildschirmfoto 2020-10-18 um 12 24 12" src="https://user-images.githubusercontent.com/932156/96364827-dbe72280-113c-11eb-9cbf-172b846a3682.png">

This is clearly due to the way the integration is loading the version selector from one layer above:

https://github.com/jimporter/mike/blob/39d6373cce9b3c9097c72ee3259389b06552fb4d/mike/themes/material/js/version-select.js#L24

My question is: is this by design? Or how should the root URL of a site be linked to the currently active, say (latest) version? I'd expect something like:

– https://squidfunk.github.io/mike-test/ -> https://squidfunk.github.io/mike-test/latest/

I think the best approach would be if `mike` would add a redirect similar to how the `mkdocs-redirects` plugin does it to the root of the project. Would that be a viable approach, or how'd you solve it?

Thanks for your efforts!

**Comment by squidfunk** [comment]
Okay, I've should have read more clearly. `mike set-default` is what I'm looking for 🤦

**Comment by jimporter** [comment]
Cool, glad to see you figured it out! There's probably room for improvement here though, so that people don't get caught out by this. I'm a little surprised that the JS was getting loaded at all, since I'd normally expect https://squidfunk.github.io/mike-test/ to be a 403 error (I think that's the right status code, anyway). However, that could just be the result of your tests leaving some old files around...

One possibility here would be a warning when running `mike deploy` to tell users that they should run `mike set-default`. That should be doable, but there are some edge cases I'll have to think through...

**Comment by squidfunk** [comment]
Native integration for mike just landed in [Material for MkDocs Insiders](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/)!

![versioning](https://user-images.githubusercontent.com/932156/97111931-ddd35780-16e1-11eb-98cb-08ff3234b748.png)

__Demo__:
https://squidfunk.github.io/mkdocs-material-example-versioning/

**Comment by jimporter** [comment]
@squidfunk Great! I'll see what I can do here to minimize the hiccups for people using the Material theme. Currently, `mike install-extras` injects version-handling JS/CSS into the user's docs, but now I'll need to check the version of the Material theme to see if the extra scripts are needed.

A warning that the user should remove old extras when upgrading might be nice too, but that's a bit trickier...

**Comment by squidfunk** [comment]
I've added a note that it's not necessary to install extras when using the Insiders version, so I think there's nothing you need to do, see:
https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#versioning
