### ISSUE TITLE
Deploying docs fails with `error: File is not a zip file`

### ISSUE THREAD

**Issue by kylebarron** [jimporter/mike#215]
# Summary

In https://github.com/developmentseed/lonboard I have a CI script that deploys mike-based documentation. Publishing docs from CI worked fine for the v0.7.1 tag but failed for the v0.8.0 tag. It fails with only the text `error: File is not a zip file`.

If it's an issue on my side, it would have to be in [this changeset](https://github.com/developmentseed/lonboard/compare/v0.7.1...v0.8.0). I don't see anything that specifically jumps out at me, but `error: File is not a zip file` isn't so descriptive that I know where to look.

I don't usually test building the docs on each pull request, but tomorrow I can go through `git bisect` for each PR and test `mike deploy` on each commit if that's helpful. `poetry run mkdocs build` still works.

# Configuration and Logs

* Repository: https://github.com/developmentseed/lonboard
* Platform: Github actions linux
* `mike` version: 2.0.0 ([`poetry.lock`](https://github.com/developmentseed/lonboard/blob/3b6e89e8946d7dfb5ac83dec4bf519d66806a783/poetry.lock#L2121-L2130))
* Commit generated by `mike`: 
* CI configuration: https://github.com/developmentseed/lonboard/blob/16d4c3ce41fbd540585b4ef3e5395cee4038e8ee/.github/workflows/deploy-mkdocs.yml
* CI logs: [This run](https://github.com/developmentseed/lonboard/actions/runs/8572127818), which errors only with:

	```
	error: File is not a zip file
	Error: Process completed with exit code 1.
	```

# Steps to Reproduce
1. 
2. 

# Expected Behavior

# Additional Context

**Comment by jimporter** [comment]
> I don't usually test building the docs on each pull request, but tomorrow I can go through `git bisect` for each PR and test `mike deploy` on each commit if that's helpful. `poetry run mkdocs build` still works.

Bisecting would definitely help, yeah. You can also get more information about the error by calling `mike --debug deploy`. That'll print the full backtrace. I'm not sure where the issue would be in mike though, since mike doesn't (intentionally) use zip files anywhere. Perhaps it's another misbehaving plugin?

**Comment by kvanzuijlen** [comment]
Please check the version of your mkdocs-material dependency. It had to be updated because a Google download was no longer available, see details here: https://github.com/squidfunk/mkdocs-material/issues/6983

**Comment by kylebarron** [comment]
> Please check the version of your mkdocs-material dependency. It had to be updated because a Google download was no longer available, see details here: [squidfunk/mkdocs-material#6983](https://github.com/squidfunk/mkdocs-material/issues/6983)

Ah thanks, this was the fix! Sorry for the noise!
