### ISSUE TITLE
`mike deploy --push version` also updates latest

### ISSUE THREAD

**Issue by shanduur** [jimporter/mike#219]
# Summary

when running Mike on dev branch (in my case `main`) resulting website is linked to "latest", which should point only to latest release.

# Configuration and Logs

* Repository: https://github.com/anza-labs/lke-operator 
* Platform: GitHub Actions 
* `mike` version: `2.1.1`
* Commit generated by `mike`: https://github.com/anza-labs/lke-operator/commit/4478d0b6adce8fedfb7d7c92b9772122915b1ea0 
* CI configuration: https://github.com/anza-labs/lke-operator/blob/main/.github/workflows/image-docs.yaml 
* CI logs: https://github.com/anza-labs/lke-operator/actions/runs/9314657264/job/25639254625 

# Steps to Reproduce
1. 
2. 

# Expected Behavior

Only `main` is updated.

# Additional Context

**Comment by jimporter** [comment]
Your CI logs indicate that nothing changed on your `gh-pages` branch, which means that the commit generated by mike was most likely generated elsewhere.

**Comment by jimporter** [comment]
Actually, another possibility would be that the "nothing changed" warning is coming from `mike set-default` here: https://github.com/anza-labs/lke-operator/blob/c06442a973f4ed866b9921d934643df84a7e8f37/hack/publish.py#L107-L109

Are you sure that `is_initial()` is returning the correct value here?

**Comment by shanduur** [comment]
Ah, yes! Sorry for that confusion!
