### ISSUE TITLE
GitHub Pages Build and Deployment Action Triggered Twice, but One Fails.

### ISSUE THREAD

**Issue by srikant-ch5** [jimporter/mike#224]
# Summary
Our requirement is to deploy documentation changes with versioning both at https://orgname.github.io/canvas/v13 and at a URL that does not include the version number, specifically /latest (https://orgname.github.io/canvas/).

To achieve this in the GitHub workflow for deploying docs, we are utilizing mkdocs and mike commands as shown below:

`- run: mkdocs gh-deploy --force`
`- run: mike deploy --push --update-aliases v13 latest`

As a consequence of this setup, two GitHub Actions for page build and deployment are being triggered simultaneously.

<img width="520" alt="Screenshot 2024-07-23 at 12 36 25 PM" src="https://github.com/user-attachments/assets/fa692448-bbb6-4291-963f-41c5a57cb7b0">

Could you please suggest a more optimal way to execute mike commands so that we can avoid the above issue?

# Configuration and Logs
<img width="925" alt="Screenshot 2024-07-23 at 12 46 39 PM" src="https://github.com/user-attachments/assets/9dfd6c05-149d-462c-850c-e080b51f5b1e">

* Repository: https://github.com/elyra-ai/canvas
* Platform: Github Actions

**Comment by jimporter** [comment]
I don't think `mkdocs gh-deploy` and `mike deploy` are likely to play nicely with each other. I think the former will wipe out any existing versioned docs you've previously deployed. You might be able to get this to work with some effort, but I think the best way forward is to not worry about it. If you want a stable URL for the latest version of your documentation, that's what aliases are there for.

You might be able to get something like what you want with a sufficiently-advanced `404.html` page (redirect unversioned paths to the default version?), but I'm not 100% sure that would work out...
