### ISSUE TITLE
Alias shown in version selector is determined randomly

### ISSUE THREAD

**Issue by connesy** [jimporter/mike#229]
When aliasing a version with multiple aliases, only one of the aliases is shown in the version selector when `alias: true` in `mkdocs.yml`. 
However, which alias is shown is random, probably due to the aliases being saved as a `set` in `VersionInfo`:
https://github.com/jimporter/mike/blob/3b425156dec71bd7cd3440f42f41b99c7013a9ce/mike/versions.py#L23

Example:
```
mike deploy 1.0.0 1.0 stable
mike serve
```
Sometimes the alias shown next to `1.0.0` in the version selector is `1.0`, sometimes it's `stable`.

**Comment by jimporter** [comment]
> When aliasing a version with multiple aliases, only one of the aliases is shown in the version selector when `alias: true` in `mkdocs.yml`. 

That's not a feature of mike, but rather with the Material theme.

> However, which alias is shown is random, probably due to the aliases being saved as a `set` in `VersionInfo`:

Correct, mike has no concept of the order of an alias: they're all of equal priority, and their primary representation is as pointers (symlinks by default) from the alias to the real version. The set of aliases in `versions.json` is just the set of backreferences from the real version to the aliases. Unfortunately, JSON doesn't have a set data structure, so it's stored as a list.

Generally speaking, I wouldn't advise a theme to automatically use aliases in the version selector widget like this. If users want the entry in the version selector to have a different string than the (real) version identifier, that's what the `title` attribute is for.
