### ISSUE TITLE
Question: remove one alias from versions.json

### ISSUE THREAD

**Issue by JavierEscobarOrtiz** [jimporter/mike#233]
Hello, 

I want to delete the `dev` alias from my 0.14.0 release. I thought that `mike alias 0.14.0 latest --push --branch gh-pages` would do the job, but it just added the alias, but did not delete `dev`. How can I do this?

Thanks a lot!

My `versions.json` looks like this:

```bash
{
    "version": "0.14.0",
    "title": "0.14.0 (stable)",
    "aliases": [
      "latest",
      "dev"
    ]
  }
```

**Comment by jimporter** [comment]
Just use `mike delete`: https://github.com/jimporter/mike?tab=readme-ov-file#deleting-docs
