### ISSUE TITLE
Change doc order

### ISSUE THREAD

**Issue by Amber1990Zhang** [jimporter/mike#27]
I noticed that if you don't `set-default` version, you can't run `mike serve` successfully. Shall we change the doc order to remind the users？

**Comment by jimporter** [comment]
Hmm, it works for me. What's the error message you're getting?

Note that if you don't have a default and just try navigating to `http://localhost:8000/` (or wherever `mike serve` is serving the docs), you'll get a 404. You need to type in the URL to a specific version, e.g. `http://localhost:8000/1.0/`.

**Comment by Amber1990Zhang** [comment]
yes as you said I got a lot 404 when trying to access the `http://localhost:8000/` directly

**Comment by jimporter** [comment]
I added a bit more explanation of what's going on to the 404 page when you navigate to `http://localhost:8000`. Hopefully that will help anyone who runs into this in the future understand what's going on and how to fix it. Thanks for the bug report!

**Comment by Amber1990Zhang** [comment]
thanks
