### ISSUE TITLE
Error while deploying

### ISSUE THREAD

**Issue by marcela-fernanda** [jimporter/mike#30]
I got this error while I was trying to run this command: `mike deploy --push --update-aliases 0.1.0 latest` (also, whith `mike install-extras` I got the same error)

Error: `mike: 'charmap' codec can't decode byte 0x81 in position 167: character maps to <undefined>`

**Comment by jimporter** [comment]
As a guess, that sounds like some invalid Unicode snuck into your `mkdocs.yml` or `versions.json` files. What version of Python are you using, and what do those files look like?

**Comment by marcela-fernanda** [comment]
The problem was, actually, accents in my `mkdocs.yml` file
