### ISSUE TITLE
Running `install-extras` command changing contents of mkdocs.yml

### ISSUE THREAD

**Issue by abhiTronix** [jimporter/mike#33]
Hey, 

Running `mike install-extras` command changing the content of `mkdocs.yml`  which should not happen, and even worse it making its formatting unsuitable for deployment. Please look into this ASAP.

```sh
mike-0.5.5 
mkdocs-1.1.2 
mkdocs-material-6.2.3
```

**Comment by jimporter** [comment]
Changing the contents of `mkdocs.yml` is the whole purpose behind `mike install-extras`: it's there to add some files to `extra_css` and `extra_js`. It does its best to maintain formatting as well as possible, but given the flexibility of YAML's formatting, it's not perfect. If you have particular formatting requirements, you'll need to fix up the formatting yourself.

That said, the docs could be clearer that this will happen so it's not a surprise to people.

**Comment by jimporter** [comment]
@abhiTronix Looking at [your commit](https://github.com/abhiTronix/vidgear/commit/d61b01d6297c503c6c6c357a19bddb04ed0edb92) that got linked here, I think I see the problem: `mike install-extras` is meant to be run only one time: when the developer is first setting up their docs to use `mike`. Generally, you should run `mike install-extras`, fix things up as needed, and then commit those changes to your primary git branch.

Later, when building your docs to deploy them, you just call `mike deploy ...`.

**Comment by abhiTronix** [comment]
> Changing the contents of mkdocs.yml is the whole purpose behind mike install-extras: it's there to add some files to extra_css and extra_js. It does its best to maintain formatting as well as possible, but given the flexibility of YAML's formatting, it's not perfect. If you have particular formatting requirements, you'll need to fix up the formatting yourself.

> mike install-extras is meant to be run only one time: when the developer is first setting up their docs to use mike

@jimporter  Thanks for clearing this up. **But can there be a way so that user can disable the changes in `mkdocs.yml` and enter everything manually, but `js` and `css` files get copied as usual.** Since if this library gets updated or a bug is fixed, and there's some changes in  `js` and `css` files, then those changes might not updated at the user's end since `mike install-extras` will be running once at starting.

**Comment by abhiTronix** [comment]
**Also, `custom_dir` value is not detected when using [custom material theme](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme) and thereby `css` and `js` files are not getting copied correctly.** I'm currently moving them manually. **Plus, If we can specify the path for both `js` and `css` files directly through a parameter then may be helpful too.**

**Comment by jimporter** [comment]
Hmm... I'm not sure how much time I'd really want to put into making `mike install-extras` work nicely, since ideally, the place for that code is in the theme itself; then I don't need to worry about a theme updating and becoming incompatible with the "extras". Happily, the Material theme does this now, although it's only available to Insiders for the time being. For the built-in MkDocs themes, I might be able to convince the MkDocs team to add direct support for mike so that `mike install-extras` could just go away entirely.

**Comment by jimporter** [comment]
Reopening this for the time being at least, so that it's on my radar of things to think about...

**Comment by jimporter** [comment]
I think the solution here is #34, so I'm going to close this in favor of that one so that it's easier to track the future work needed. Thanks for filing the issue! It's made me realize the current API is a bit lacking...
