### ISSUE TITLE
404 on image relative links.

### ISSUE THREAD

**Issue by jacobswe** [jimporter/mike#36]
Relative links show 404 for images while resolving for markdown_include tables. Using insiders for material, spent about a day trying to figure out what's happening (upgrade, downgrade, etc.) but cannot get these image links to resolve. They work fine in an mkdocs serve but fail to resolve in the mike serve.

**Comment by jacobswe** [comment]
I raised this with material, but was pointed here since it seems like a solely mike issue (or user issue lol)

**Comment by jacobswe** [comment]
Mike does not handle scrubbing spaces out of links like mkdocs does, so was causing errors. Maybe in the future this could be helpful.

**Comment by jimporter** [comment]
I wasn't aware that was an MkDocs feature, actually! mike doesn't do anything special with links, and just defers all that logic to vanilla MkDocs.
