### ISSUE TITLE
Custom templates/index.html

### ISSUE THREAD

**Issue by PaulJacobs-percona** [jimporter/mike#37]
How can I override the default templates/index.html with my own?

Not using GitHub pages or the gh-pages branch but a named branch from which content is copied to a CMS (Drupal).
I use a custom theme to create an HTML block for Drupal, so anything in `<head>` elements is ignored.
The default `templates/index.html`, where the `script` redirect is in the head, doesn't work.

**Comment by jimporter** [comment]
You should be able to just check out your `gh-pages` branch, edit the `index.html` file, and commit it. The `set-default` command is really just an automated version of doing the same thing.

**Comment by PaulJacobs-percona** [comment]
Thanks, I'm doing that now but would prefer to use standard commands for changing defaults.
Use case:
A GH action workflow calls `mike deploy X.Y -b publish -p`. A separate (internal to company) step copies the whole `publish` branch to the webserver. Putting the same action file in each branch of docs means they get built and added to the `publish` branch automagically. I was looking for a way to automate the `set-default` step.
