### ISSUE TITLE
Read `remote_branch` and `remote_name` from mkdocs.yml

### ISSUE THREAD

**Issue by hadim** [jimporter/mike#38]
I use `privpage` instead of `gh-pages`. Is that supported in mike?

**Comment by jimporter** [comment]
Yes. Every command that works with the `gh-pages` branch also accepts a `-b`/`--branch` option to change the pages branch.

**Comment by hadim** [comment]
Oh ok thank you. I thought the config from mkdocs were used automatically.

**Comment by jimporter** [comment]
mike tries to use the MkDocs config by default where possible, but it doesn't currently read from `remote_branch` or `remote_name` in the `mkdocs.yml`. That's a good idea though, so I'll reopen this to keep track of adding support for it.

Thanks for the report!
