### ISSUE TITLE
BrokenPipeError when running in Azure Devops Pipeline

### ISSUE THREAD

**Issue by wbekerom** [jimporter/mike#39]
@jimporter first off: lovely project!

I'm trying to deploy and publish in an Azure Devops pipeline, but I'm running into an `BrokenPipeError`. Locally everything works fine. Was able to pinpoint the error to `stdin.write()` when committing the files, but lack the knowledge of subprocess to solve it. I did print the filenames that are being committed and there is variation in when the error occurs, sometimes after the 2nd file, sometimes after the 5th, etc.

Both systems are ubuntu-20.04. Googling suggested it might be related to buffering, so inspected `io.DEFAULT_BUFFER_SIZE` and `PYTHONUNBUFFERED` and they are are the same locally and on the pipeline agent.

 Any thought on what could be the issue?

```
+ mike deploy -u -F mkdocs/mkdocs.yml 0.1 latest
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/vsts/work/1/s/mkdocs/site 
INFO    -  Documentation built in 0.22 seconds 
Traceback (most recent call last):
  File "/home/vsts/work/1/s/mike/mike/commands.py", line 53, in deploy
    commit.add_file(f.copy(d, site_dir))
  File "/home/vsts/work/1/s/mike/mike/git_utils.py", line 202, in add_file
    self._write(file_info.data)
  File "/home/vsts/work/1/s/mike/mike/git_utils.py", line 172, in _write
    return self._pipe.stdin.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vsts/work/1/s/mike/mike/driver.py", line 240, in main
    return args.func(args)
  File "/home/vsts/work/1/s/mike/mike/driver.py", line 77, in deploy
    commands.deploy(cfg.site_dir, args.version, args.title, args.alias,
  File "/home/vsts/work/1/s/mike/mike/commands.py", line 55, in deploy
    commit.add_file(make_nojekyll())
  File "/home/vsts/work/1/s/mike/mike/git_utils.py", line 165, in __exit__
    self.abort()
  File "/home/vsts/work/1/s/mike/mike/git_utils.py", line 220, in abort
    self._pipe.stdin.close()
BrokenPipeError: [Errno 32] Broken pipe
mike: [Errno 32] Broken pipe
```

**Comment by jimporter** [comment]
Hmmm, I've never seen this particular issue. I'm sort of surprised that it fails on Azure Devops since all this code is being tested via GH Actions, which are on Azure too if I understand things correctly.

If I had to guess, `git fast-import` is failing somehow, so the process exits and breaks the pipe. You might be able to get some useful error logs by applying this patch:

```diff
diff --git a/mike/git_utils.py b/mike/git_utils.py
index a3c987e..767822f 100644
--- a/mike/git_utils.py
+++ b/mike/git_utils.py
@@ -150,8 +150,8 @@ class FileInfo:
 
 class Commit:
     def __init__(self, branch, message):
-        cmd = ['git', 'fast-import', '--date-format=raw', '--quiet', '--done']
-        self._pipe = sp.Popen(cmd, stdin=sp.PIPE, stderr=sp.DEVNULL,
+        cmd = ['git', 'fast-import', '--date-format=raw', '--done']
+        self._pipe = sp.Popen(cmd, stdin=sp.PIPE,
                               universal_newlines=False)
         self._start_commit(branch, message)
         self._finished = False
```

That should let errors/statistics from `git fast-import` bubble up to your terminal.

**Comment by wbekerom** [comment]
Using your instructions I was able to get the error from `git fast-import`:
```
fatal: Missing > in ident string: Azure Devops Pipeline <<>> 1614504842 +0000
```
Which I was able to trace back to the fact that I tried to execute using an empty email in git, I did `git config --global user.email '<>'`. It runs smoothly now, thanks for the support!

**Comment by jimporter** [comment]
Reopening this to track two fixes (though I may only need to do one of these):
* [ ] Handle empty email addresses
* [ ] Report stderr output from `git fast-import` if it failed
