### ISSUE TITLE
Redirects works with JavaScript only

### ISSUE THREAD

**Issue by oprypin** [jimporter/mike#41]
Currently people who visit the site without JavaScript enabled (and also probably some search engine robots) just see a blank page instead of being redirected.

For reference, currently a redirect page looks like this
```html
<!DOCTYPE html>
<html>
<head>
  <title>Redirecting</title>
  <script>
    window.location.replace("../0.10.0/index.html");
  </script>
</head>
<body>
</body>
</html>
```

I would suggest adding a "META redirect" and also as a last resort just render a clickable link. 
Even one of the two would help greatly.

A redirect page like this one has worked very well for me:

https://github.com/oprypin/crsfml/blob/1d98a31d96409e6b849e70414ac9407b7586d8f0/index.html

Cheers on using `.replace` in JavaScript, I hadn't realized that [it's the better way](https://stackoverflow.com/a/7703736), so don't take that part from me :sweat_smile:

**Comment by jimporter** [comment]
Yeah, that seems like a good idea! I put the `<meta>` redirect inside `<noscript>` tags too, just to be extra-safe in keeping it from running when JS is enabled; in that case, we want to use `window.location.replace`, since it's nicer.
