### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by LilTrublMakr** [jimporter/mike#43]
I am starting to experiment on versioning on documentation for a project and noticed today that Material now has a public release of Mike for versioning.

1: I have been trying to get it to work without having to push changes to GitHub and am having problems with doing that.

I have added
```
extra:
  version:
    provider: mike
```
in to my mkdocs.yml file and tried `mike deploy 1.5 latest` and it seems to build the documentation fine. However, when I use either `mkdocs serve` or `mike serve`, nothing changes. I don't see a dropdown to select a version or anything. When I do `mike list`, I see the versions that I have made.

2: I see that there is an area on the index page explaining that there is a way for me to be able to add pages to the documentation without being versioned. I am not clear on the procedure on how to do this though. I want to put a few paged in a non versioned like an index page, news page, FaQ page, and update log. I see that I should be able to put it in the root directory with mkdocs.yml but then it doesn't get included when building. Am I missing something in this area?

3: I have documentation for multiple versions already. Right now, I just have them in folders in /docs. To split them out in to Mike versions, do I need to just add them one at a time, push the version, replace the content with a new version, and repeat? If you need clarification on this, let me know.

4. If I need to edit a previous version, is there a way of doing that?

**Comment by jimporter** [comment]
1. Are you just looking at the root of your server (`localhost:8000/`)? If so, you're looking at your old, unversioned docs. Try `localhost:8000/1.5/`.
2. To add unversioned files, just check out the `gh-pages` branch and add them there (or add files to the `gh-pages` branch via some other tool, of course). mike doesn't care about other files in your `gh-pages` branch, so you can add whatever you need.
3. It really depends on what you want to do. So long as you put them in a subdirectory for each version (`/1.0/`, `/2.0/`, etc) and refer to them via `/versions.json`, mike will be happy. For your case, you could probably just manually create the `versions.json` file.
4. Yes, just run `mike deploy [old-version]`. If the old version has aliases associated with it, they'll automatically be updated too.

**Comment by LilTrublMakr** [comment]
1. Yes I am. Looking at localhost:8000/1.5/ takes me to a 404 on the local environment but was somehow pushed to live.

2. So this means that I would push the documentation to live, then checkout (will have to look that up) the `gh-pages` branch, add in the missing already built pages, and then push them again?

3. I am not seeing a `versions.json` file in my files. I looked in both `/docs` and `/site`. Where should I create it and is there any documentation on how it is formatted?

4. Nice. So as long as I keep the folders as `/1.0/`, `/1.1/`, `/1.2/`, etc, and then edit the file contents for a specific version and push the changes, it will only change that version?

Sorry for all the questions, I am just trying to figure out how this all works since there isn't too much documentation on here or Material to go off of. At this point, I might also just restart the documentation for this project and upload them in order instead of trying to get them all up at once.

**Comment by jimporter** [comment]
1. Be sure you run `mike serve` there, since `mkdocs serve` works differently; the former serves from your local copy of the `gh-pages` branch, while the latter serves from the `site/` directory (which usually isn't under version control).
2. You don't have to push the documentation until you're ready, but yes, you'll want to add any extra, unversioned files to the appropriate location in your `gh-pages` branch.
3. It should be in your `gh-pages` branch at the root. For example, see https://github.com/squidfunk/mkdocs-material-example-versioning/tree/gh-pages
4. Yes, `mike deploy 1.0` will only make changes within `/1.0/`, plus any aliases you've set for 1.0; in your example above, `mike deploy 1.5 latest` sets `latest` to be an alias for `1.5`, so if you call `mike deploy 1.5` later, it remembers that `latest` is an alias for `1.5`, so it updates *both* `/1.5/` and `/latest/`.

**Comment by jimporter** [comment]
Closing this as there haven't been any updates since my last reply; if you still have questions, feel free to reply here.

**Comment by LilTrublMakr** [comment]
Sorry, work has been... Crazy... So I haven't had time to work on this project.

I am still having a hard time using the versioning. I think I am just going to start a new project and then add the content available to that particular version and then push it and then update the content to the next version and so on.

One thing I am stull confused on is the static pages. It sounds to me that I need to deploy the docs, pull them from a different branch, add the pages that I would like static, and then push them again. Is this correct?

**Comment by jimporter** [comment]
> One thing I am stull confused on is the static pages. It sounds to me that I need to deploy the docs, pull them from a different branch, add the pages that I would like static, and then push them again. Is this correct?

Ultimately, most of what mike does is to just generate git commits on your `gh-pages` branch. Since it's just a branch full of static files, you can also add any other files you want via the usual git commands. An example workflow might help here:

```sh
cd /path/to/repository
git checkout gh-pages
edit my_static_file.html
git commit -a
git push
```
