### ISSUE TITLE
Add trailing slash to version selector URL's

### ISSUE THREAD

**Issue by wbekerom** [jimporter/mike#46]
URL's in version selector need a trailing slash in order to be in line with other links in generated docs. This ensures that the relative paths to js / css always work. For me the URL's did not work when deploying to Azure blob storage, hosted as "static website".

This probably needs to be fixed in `templates/redirect.html` and `version-select.js` in both themes. 
I can send you a PR for this if you like.

Similar to: https://github.com/squidfunk/mkdocs-material/pull/2434

**Comment by jimporter** [comment]
Fixed in 79827d4b1d75f9786fe630d2b688c3ddbd354ca7 and 05eb98ca36c5be6dab06a7d7acb05d1a884894fc

**Comment by wbekerom** [comment]
Thanks!
