### ISSUE TITLE
--prefix argument not available in current pip release

### ISSUE THREAD

**Issue by ithier** [jimporter/mike#47]
[This change](https://github.com/jimporter/mike/commit/7cff0cc9bd434ff2db8d7c8c945d2a6befcba85f) adds the really nice feature of specifying a directory prefix. This is especially nice when using `mike` with GitLab since GitLab pages expect artifacts in a directory named `public` within the repo.

Are there any plans to make a new release sometime soon ?

**Comment by jimporter** [comment]
Yes, but it'll probably be a couple weeks. I've still got some cleanup to do and final testing to ensure there aren't any (obvious) bugs before I can publish 1.0.

**Comment by ithier** [comment]
Sounds great ! Thanks for the update.

**Comment by jimporter** [comment]
1.0.0 is available on PyPI now: https://pypi.org/project/mike/1.0.0/
