### ISSUE TITLE
URLs in sitemap.xml do not include version part

### ISSUE THREAD

**Issue by squidfunk** [jimporter/mike#50]
When using `mike` for versioning, the URLs which are listed as part of the `sitemap.xml` do not include the version part. As an example, see the [versioning demo](https://github.com/squidfunk/mkdocs-material-example-versioning/blob/gh-pages/0.2/sitemap.xml) I created, which suffers from this behavior:

Actual result:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url>
     <loc>https://squidfunk.github.io/mkdocs-material-example-versioning/</loc>
     <lastmod>2021-03-29</lastmod>
     <changefreq>daily</changefreq>
    </url>
</urlset>
```

Expected result:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url>
     <loc>https://squidfunk.github.io/mkdocs-material-example-versioning/0.4/</loc>
     <lastmod>2021-03-29</lastmod>
     <changefreq>daily</changefreq>
    </url>
</urlset>
```

This issue is more or less meant as a question where this is done by design or was accidentally forgotten. With the URLs not being correct, submitting the `sitemap.xml` to search indexes might not work as expected.

**Comment by jimporter** [comment]
Are you testing this with mike 0.5.5? I think this should be fixed by bf4f54f9e8d5a2ff70bf7d071e659e725e85866a, which will be in 1.0 (to be released today or tomorrow).

**Comment by squidfunk** [comment]
I've used 0.5.5, but I'll give 1.0 a try!

**Comment by squidfunk** [comment]
It's indeed fixed. Thanks for your work on this project!
