### ISSUE TITLE
How to get started? README.md doesn't help.

### ISSUE THREAD

**Issue by samthesuperhero** [jimporter/mike#53]
Dear Contributors,

I use:

- [`mkdocs`](https://www.mkdocs.org/)
- [`mkdocs-material`](https://squidfunk.github.io/mkdocs-material/)

All is OK with `mkdocs` and `mkdocs-material` - everything is built and running both on local (with `mkdocs serve`) and on my web server - site by URL is fully functional!

And with `mike`:

1. I made `git init` in the source dir with my mkdocs material sources
2. Then, did `add` and `commit`
3. Then, run `mike deploy 0.1 dev` and `mike deploy 0.2 new`
4. I see that in my `site_dir` directory there are rendered web files
5. I deploy that web files to my web server,
6. I don't see the version selector
7. Then locally I do `mike serve`
8. Locally at `http://localhost:8000` I see that **version selector appears**!!

What do I do wrong?

Why there are no explanations about such cases in README.md for those like me who are out of context?

+ question: when I deploy new version, where that version is saved? git doesn't show any changes in the repo sources when I do deploy

**Comment by jimporter** [comment]
You need to serve the contents of your `gh-pages` branch. The `site` directory is just a temporary staging location for the generated docs.

**Comment by samthesuperhero** [comment]
Works, super, thx!! Maybe worth adding to docs for newcomers ;)
