### ISSUE TITLE
Run mike with non-default mkdocs.yml file?

### ISSUE THREAD

**Issue by PaulJacobs-percona** [jimporter/mike#56]
I have three mkdocs-*.yml files; one default, one for PDF generation and one for transitioning to and testing netlify.
Is there any plan to include an equivalent to the `mkdocs build -f` option for mike?
Is there any way to specify non-default mkdocs config file when running mike?
Thanks

**Comment by jimporter** [comment]
Yes, `-F`/`--config-file` will let you specify the file to use.
