### ISSUE TITLE
Mike breaks Umlaute in nav tabs when deploying

### ISSUE THREAD

**Issue by hpsem** [jimporter/mike#63]
I noticed a Problem with Mike 1.0.1 when deploying my docs with `mike depoy`: 

![image](https://user-images.githubusercontent.com/78910056/125055877-f6d13c80-e0a7-11eb-9a46-24dcd8d7418d.png)

As you can see it breaks Umlaute in the navigation tabs and the repository Name.

When i serve with mkdocs it works fine. `mkdocs serve`:

![image](https://user-images.githubusercontent.com/78910056/125056204-49aaf400-e0a8-11eb-99c2-3d75df2eb0bb.png)

Im using mike 1.0.1 and mkdocs 1.2.1

Any help or suggestions are greatly appreciated! :-)

**Comment by jimporter** [comment]
I've tried a few different configurations, and this works fine for me everywhere as far as I can tell. Do you have a repository I could look at? It's possible the encoding you're using in your `mkdocs.yml` is causing the issue.

As a workaround, you could try adding the `mike` plugin to your config (see the README for details). If the plugin isn't listed, mike writes a temporary `mike-mkdocs.yml` file, and that might be getting mis-encoded.

**Comment by hpsem** [comment]
Adding mike to the plugins solved the issue! Thank you very much for the suggestion! my mkdocs.yml is utf-8 encoded so this should be fine, I assume?

**Comment by jimporter** [comment]
UTF-8 should be fine. I'm not sure why it's not working, but presumably something bad is happening when writing the temporary `mkdocs.yml` (which mike does when the `mike` plugin isn't listed).
