### ISSUE TITLE
Add support for multi-language documentations

### ISSUE THREAD

**Issue by hmsdoc** [jimporter/mike#73]
Hi @jimporter, mike works great with single-language documentations. But as far as I can understand, it is currently not possible to use it with multi-language documents that are created as described in [this](https://github.com/squidfunk/mkdocs-material/discussions/2346) MkDocs Material discussion.

If so, is there a workaround you can recommend, that enables a combination of the multi-language and versioning features? Or are you planning to include this in a future version?

Thanks in advance!

**Comment by jimporter** [comment]
You can use `--prefix=LANG` to put your docs within `LANG/` as a subdirectory. Then you'd have `example.com/LANG/VERSION/...`. Each language would be 100% independent of each other, so you'd have to be sure to keep them in sync, but that shouldn't be much extra work if you've got tooling set up for it.

Based on that link, it looks like this would work pretty much the same, with the caveat that you'd be generating one commit per language; I don't really see that as an issue, but if you don't like that, it should be straightforward to squash the commits before pushing upstream.

**Comment by hmsdoc** [comment]
Thank you very much for your suggestion! It worked exactly as you described. I was able to achieve the expected result via a GitLab Pages pipeline by adding the `--prefix` parameter and changing into the correct subdirectory to call mike for the corresponding language. I'm fine with having multiple commits (one per language).
