### ISSUE TITLE
❓ How to use `mike` locally ?

### ISSUE THREAD

**Issue by ghost** [jimporter/mike#77]
I would like to use `mike`, but I don't want to host my docs on github pages.

If possible, I would like to avoid `mike` committing anything to my branches.

---

**So is it possible to use `mike`  so that the docs versions are stored locally (as in : in the current branch), and let me commit the changes by myself ?**

_I'm not sure I'm very clear, feel free to ask for clarifications ! Thanks for your patience._

**Comment by jdomag** [comment]
@squidfunk @jimporter 
How to use versioning then in Material without mike and host it with e.g. nginx? Is the structure of versions.json described somewhere?

**Comment by squidfunk** [comment]
@jdomag https://github.com/jimporter/mike/issues/80#issuecomment-962273298

**Comment by jimporter** [comment]
> Is the structure of versions.json described somewhere?

It's at the end of the README: https://github.com/jimporter/mike#for-theme-authors
