### ISSUE TITLE
Large file sizes and long build time

### ISSUE THREAD

**Issue by malohr** [jimporter/mike#86]
So Im not sure if this a normal behaviour, but basically im facing some issues with two things:
1. Long build time (approx. 20-30 minutes when mkdocs-minify-plugin is active otherwise its a bit quicker)
2. HTML file sizes are pretty large in my opinion (around 1.5MB each)

I have about 4000+ .md files that are going to be build so as I said Im not sure if this is "normal".

Of course after the build, the site folder has a total size of 5GB which makes it very hard to deploy the docs in a docker image

**Comment by jimporter** [comment]
How does the performance compare when using vanilla MkDocs? If mike is much worse than MkDocs, there might be some room for performance improvements, but this is well beyond the size range mike is designed for. At sizes like that, it's probably not the best idea to be storing each update of your docs in a Git branch of your repository.

**Comment by jimporter** [comment]
No response, so closing this issue.
