### ISSUE TITLE
set default function not working

### ISSUE THREAD

**Issue by jerrywheeler** [jimporter/mike#91]
https://intel-secl.github.io/docs/ 

we have set 4.1 as the default but is does not go to 4.1 or 4.0 if we set it..

you can see the architecture in the above repro

**Comment by jimporter** [comment]
This seems to be working correctly at the time of my message. However, it appears you didn't run `mike delete --all` (see the README), so you have some stale unversioned files in your `gh-pages` branch from running `mkdocs` directly.

**Comment by jerrywheeler** [comment]
I cant get the versioning option to show up at https://intel-secl.github.io/docs/

If I goto https://intel-secl.github.io/docs/4.1 then it shows up

I ran mike delete --all before redeploying the updated docs

**Comment by jimporter** [comment]
At some point after setting the default to 4.1 (see [this commit](https://github.com/intel-secl/docs/commit/6af7ce48aafc471f5cca67efab8cc54bbaa2e016)), you ran `mkdocs gh-deploy`, replacing the root `index.html` in [this commit](https://github.com/intel-secl/docs/commit/6125b017ce8e9e6bae8b0a38b9991f849a5b9fa7). If you overwrite `index.html` like that, then you'll lose the redirection behavior you want.

**Comment by jerrywheeler** [comment]
so after i push my new code,

what would the order be?
mkdocs gh-deploy
run mike deploy (version) --push for all 3 versions 
then run mike set-default 4.1

**Comment by jimporter** [comment]
You should never be running `mkdocs gh-deploy`. That's only for deploying unversioned documentation.

**Comment by jerrywheeler** [comment]
ok, so commit my new code

run:
mike deploy 4.0 --push
mike deploy 4.0.1 --push
mike deploy 4.1 --push
mike set-default 4.1

**Comment by jimporter** [comment]
Generally speaking, you only need to call `mike set-default` if the default has actually changed. For the deploy commands, that's really up to you how you want your resulting docs to be structured. The README explains the various options for deploying in more detail.

**Comment by jimporter** [comment]
If you delete everything (with `mike delete --all`), then yes, you would need to call `mike set-default` again. However, as the README describes, `mike delete --all` is useful for when "you have existing documentation on your `gh-pages` branch" before you start using mike, so you only need to run that once.

If you're still confused about what's happening, I recommend examining the commit history generated on your `gh-pages` branch. It should then be clearer what each command you're running actually does.

**Comment by jerrywheeler** [comment]
thanks for your help, I finally got it working
