### ISSUE TITLE
Pages that should always display the most recent content

### ISSUE THREAD

**Issue by ofek** [jimporter/mike#97]
Ref: https://github.com/squidfunk/mkdocs-material/discussions/3746

Is there/could there be a way for certain pages to always display the most recent content? My use case is for a list of downstream users, and possibly the changelog.

Essentially, I want `/X.Y.Z/users` to always show what's on master or redirect to/display `/dev/users` that is always built from master. Or maybe better yet, outside the scheme like `/users`.

**Comment by jimporter** [comment]
Each version of the docs is 100% independent, so there's no automatic solution for this. However, you could deploy some non-versioned documentation (which would really just be a totally different MkDocs build deployed alongside the versioned docs) and then cross-link/redirect as needed between versioned and unversioned pages.

**Comment by jimporter** [comment]
Based on my above comment, I don't think there's anything else to do here. However, if it's not working for you, feel free to comment again and I can try and point you in the right direction.
